### ISSUE TITLE
Deal with queries between normal resources and the separate lookup fields.

### ISSUE THREAD

**Issue by darnjo** [RESOStandards/reso-web-api-reference-server#6]
Since we're putting the lookup values for multi-lookups in their own table, we'll need to make special considerations where queries are concerned. 

* If the query is not for any of the lookup fields, then do the query on the resource table first, get keys, and do fetch on LookupValue by keys.
* If the query is for any of the lookup fields (could be more than one), query LookupValue first, get keys from it, and then fetch from the resource table by those keys.
* If the query is on both resource and lookup values, query both sets (in parallel) and then determine the intersection where both criteria are valid, accounting for ands, ors, and nots.

**Comment by michaelpede** [comment]
Some clarification is needed for single value lookup fields.  They can either exist as values on the resource table, or in the Lookup value table, like a Multi-value, except single.
I'm going under the assumption that both ways should be supported, although we are currently reading the single-values from the lookup_value table.  If we only want to support one for now, that would simplify the code.

**Comment by darnjo** [comment]
This can be closed - this is NOT the correct direction for this project as we don't want to store multiple lookups in a separate table, but rather with their actual records.

Look into the JSON data type in MariaDB for this - we need to be careful of the size of a row though, because we've already exceeded the rowsize limit with Varchars and other data types. Needs to behave more like TEXT where the size isn't counted in the rowsize beyond the basic storage requirements.
